version: '3.8'
services:
  app:
    image: mcr.microsoft.com/devcontainers/typescript-node:18
    volumes:
      - ..:/workspace
    command: sleep infinity
    network_mode: service:supabase

  supabase:
    image: supabase/postgres:15.1.0.89
    environment:
      POSTGRES_PASSWORD: postgres
    volumes:
      - supabase_data:/var/lib/postgresql/data
    ports:
      - 54322:5432
      - 54323:3001 # Studio

volumes:
  supabase_data:
